#!/usr/bin/python3
>>> from django.db import models
>>> from django_cryptography.fields import encrypt
# django.core.exceptions.ImproperlyConfigured: Requested setting CRYPTOGRAPHY_BACKEND, but settings are missconfigured. 
# You must either define the environment variable DJANGO_SETTINGS_MODULE, call settings.configure() before accessi ng settings.
>>> class Model(models.Model):
...     name = models.CharField(max_length=50)
...     sensitive = encrypt(models.CharField(max_length=50))
... 

#Other cryptographic examples-SIGNATURES
>>> import binascii
>>> import struct
>>> import zlib
>> from  typing import Any, Optional, Type, Union
>>> from cryptography.hazmat.primitives.hmac import HMAC
>>> from django.conf import settings
>>> from django.core.signing import (
...     BadSignature,
...     JSONSerializer
...     SignatureExpired,
        b64_decode,
        b64_encode,
        get_cookie_signer,
)

